### ISSUE TITLE
PhotonVision Networking Setup

### ISSUE THREAD

**Issue by DrewTheRat** [Mercury1089/2023-robot-code#12]
We have two PhotonVision co-processors on the robot. Both need to have their networking settings finalized. They need the following:
- Unique static IP address
- Unique hostname
- Team number set (for network table)

Instructions for updating these settings can be found here: https://docs.photonvision.org/en/latest/docs/getting-started/installation/networking.html
I propose the following settings:
- [ ] AprilTag Raspberry Pi 4b
  - Hostname: photonvision-apriltag
  - IP Address: 10.10.89.11
- [ ] Claw Cam Raspberry Pi 3b
  - Hostname: photonvision-claw
  - IP Address: 10.10.89.12

To access and apply these settings, do the following:
1. Power up just that Raspberry Pi (i.e. unplug the one you're not updating)
2. Try browsing to photonvision.local:5800. If that works, skip step 3.
3. Find the IP address using the Angry IP Scanner tool. It should be installed. Browse to _IP-Address_:5800
4. Follow the instructions on the [PhotonVision Docs - Networking] section to apply the settings above.
5. Save the and test the settings.
  1. Ping the static IP you just set to make sure it works
  2. Browse to _new-hostname_.local:5800 and make sure it comes up
  3. If the hostname doesn't work, try _new-ip-address_:5800 - this should work.
  4. If you cannot see the updated IP, start from step 3 above to find the current IP

**Comment by rshah713** [comment]
```
PS C:\Users\Mercury1089\git\2023-robot-code> ping 10.10.89.12

Pinging 10.10.89.12 with 32 bytes of data:
Reply from 10.10.89.12: bytes=32 time=2ms TTL=63
Reply from 10.10.89.12: bytes=32 time=2ms TTL=63
Reply from 10.10.89.12: bytes=32 time=2ms TTL=63
Reply from 10.10.89.12: bytes=32 time=2ms TTL=63

Ping statistics for 10.10.89.12:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss)
```

Thanks for the helpful instructions!

**Comment by rshah713** [comment]
```
PS C:\Users\Mercury1089\git\2023-robot-code> ping 10.10.89.12

Pinging 10.10.89.12 with 32 bytes of data:
Reply from 10.10.89.12: bytes=32 time=2ms TTL=63
Reply from 10.10.89.12: bytes=32 time=2ms TTL=63
Reply from 10.10.89.12: bytes=32 time=2ms TTL=63
Reply from 10.10.89.12: bytes=32 time=2ms TTL=63

Ping statistics for 10.10.89.12:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss)
```
Thanks for the helpful instructions!
