### ISSUE TITLE
Update Robot Swerve Configuration

### ISSUE THREAD

**Issue by DrewTheRat** [Mercury1089/2023-robot-code#15]
The front of the robot changed. We mounted the claw mast on what was one side of the robot. We need to update the swerve module config to compensate. 

Use the REV tool to check the CAN IDs of each SPARKMax. Either update the SPARKs to match the code or update the code to match the sparks.

Also, make sure the absolute encoders settings are good. Use the swerve module tool that locks the wheel in position, then go to the Absolute Encoder tab of the SPARKMax. Make sure it is zeroed out. (This is done in the REV tool while connected via USB-C cable).

**Comment by rshah713** [comment]
CAN IDs changed based on physical robot. REV tool used to set absolute zero of SPARKMax's.
