### ISSUE TITLE
[DriveTrain] Add PhotonPoseEstimator to code

### ISSUE THREAD

**Issue by DrewTheRat** [Mercury1089/2023-robot-code#5]
`PhotonPoseEstimator` is a class provided by PhotonVision to estimate the robot field pose based on one or more AprilTag targets. The measurements from PhotonVision are fed to the `SwerveDrivePoseEstimator` (see Issue #1 ). More on `PhotonPoseEstimator` [here](https://docs.photonvision.org/en/latest/docs/programming/photonlib/robot-pose-estimator.html).

1. Add PhotonLib to the robot project ([instructions here](https://docs.photonvision.org/en/latest/docs/programming/photonlib/adding-vendordep.html))
2. Create a wrapper class for the `PhotonPoseEstimator` that will keep track of camera names, etc.
3. Create the `AprilTagFieldLayout` object in this wrapper class and initialize with with the field layout JSON file
4. Update the `DriveTrain` subsystem to pull update odometry with the vision estimation (in the periodic method)

**Comment by DrewTheRat** [comment]
The AprilTagFieldLayoutJson is here: https://github.com/wpilibsuite/allwpilib/blob/main/apriltag/src/main/native/resources/edu/wpi/first/apriltag/2023-chargedup.json

**Comment by rshah713** [comment]
Note we do not need to add this to our repo separately. We should use the constant `AprilTagFields.k2023ChargedUp.m_resourceFile` which holds the path to the file, and pass it into `loadFromResource()`
